### ISSUE TITLE
Wrong lexorank when using genNext

### ISSUE THREAD

**Issue by traed** [kvandake/lexorank-ts#8]
```
const m = '0|14b0rx2:';
const n = LexoRank.parse(m).genNext().toString();

console.log(`Prev: ${m}, next: ${n}, correct: ${m < n}`);
// Prev: 0|14b0rx2:, next: 0|125idyi:i, correct: false
```

Tested on a fresh node server with no other dependencies than lexorank. `genPrev` seems to work fine but not this.

**Comment by loicbisiere** [comment]
I think it's correct, it's your verification operator that doesn't apply here.

**Comment by Kannndev** [comment]
@traed Did you fork and change anything because the ranking character before `:` should be in 6 character length and Here i see you have 7. It seems to produce wrong result with any 7 characters.

**Comment by traed** [comment]
No, but we might have messed around in the database at some point resulting in incorrect values. I figured that out as well but we ended up making our own implementation since we preferred having a variable length string.

**Comment by Kannndev** [comment]
@traed Do you mind sharing the custom implementation. It would be of great help.
